{
	"version": 1746885175,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/platform-sheet0.png",
		"images/player-sheet0.png",
		"images/camera-sheet0.png",
		"images/playermask-sheet0.png",
		"images/playermask-sheet1.png",
		"images/towerbg.png",
		"images/grass.png",
		"images/crate-sheet0.png",
		"images/playerprojectile-sheet0.png",
		"images/playergun-sheet0.png",
		"images/moneyparticles.png",
		"images/jumpthru-sheet0.png",
		"images/health.png",
		"images/spikes-sheet0.png",
		"images/crateparticles.png",
		"images/item-sheet0.png",
		"images/item-sheet1.png",
		"images/item-sheet2.png",
		"images/titlething-sheet0.png",
		"images/fallingmoney-sheet0.png",
		"images/trumpmoneyhead-sheet0.png",
		"images/towersign-sheet0.png",
		"images/pointlessbutton-sheet0.png",
		"images/pointlessbutton-sheet1.png",
		"images/enemy-sheet0.png",
		"images/enemygun-sheet0.png",
		"images/enemyprojectile-sheet0.png",
		"images/enemyprojectile-sheet1.png",
		"images/ligtningparticles.png",
		"images/timebg-sheet0.png",
		"images/button-sheet0.png",
		"images/button-sheet1.png",
		"images/trigger-sheet0.png",
		"images/darkness-sheet0.png",
		"images/submitbutton-sheet0.png",
		"images/celinglights-sheet0.png",
		"images/light-sheet0.png",
		"images/meface-sheet0.png",
		"images/sprite-sheet0.png",
		"media/ball hit wall sound.m4a",
		"media/ball hit wall sound.ogg",
		"media/get those lights off wav.m4a",
		"media/get those lights off wav.ogg",
		"media/we're win win win wav.m4a",
		"media/we're win win win wav.ogg",
		"media/so tired of winning wav.m4a",
		"media/so tired of winning wav.ogg",
		"media/bing bing bong wav.m4a",
		"media/bing bing bong wav.ogg",
		"media/noooo wav.m4a",
		"media/noooo wav.ogg",
		"media/zzzzt wav.m4a",
		"media/zzzzt wav.ogg",
		"media/zzzzt wav loud.m4a",
		"media/zzzzt wav loud.ogg",
		"media/turn off the lights chant wav.m4a",
		"media/turn off the lights chant wav.ogg",
		"media/billions wav.m4a",
		"media/billions wav.ogg",
		"media/trump mega mix wav trimmed.m4a",
		"media/trump mega mix wav trimmed.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}